---
- name: deploy flask app
  hosts: webservers
  roles:
    - role: flask
      tags: flask

- name: deploy mariadb
  hosts: dbservers
  roles:
    - role: dbserver
      tags: mariadb

- name: deploy haproxy
  hosts: haproxy
  roles:
    - role: haproxy
      tags: haproxy
