---
- name: deploy flask app
  hosts: webserver
  roles:
    - role: flask
      tags: flask
    - role: haproxy
      tags: haproxy

- name: deploy mariadb
  hosts: dbservers
  roles:
    - role: dbserver
      tags: mariadb
