---
- name: Ensure /home/vt_admin directory exist
  become: true
  file:
    path: /home/vt_admin
    state: directory
    mode: 0755
- name: Ensure deploy_folder directory exist
  become: true
  file:
    path: "{{ deploy_folder }}"
    state: directory
    mode: 0755
- name: clone the source code of flask webserver
  become: true
  git: 
    repo: "{{ flask_repo }}"
    dest: "{{ deploy_folder }}"
- name: create python virtualenv
  become: true
  command: virtualenv {{ venv_folder }} -p python2.7
- name: Install requirements
  become: true
  pip: 
    requirements: "{{ deploy_folder }}/flask/requirements.txt"
    virtualenv: "{{ venv_folder }}"
    virtualenv_python: python3.4
- name: create a service in systemd 
  become: true
  template:
    src: app.service.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
  notify: restart flask
