---
- name: install apt packages
  package: 
    name: "{{ item }}"
    update_cache: yes 
    state: present
  become: True
  with_items:
    - git
    - python-dev
    - python-pip
    - python-virtualenv

- include: flask.yml