---
- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mariadb_packages }}"

- name: enable mariadb
  service:
    name: '{{ mariadb_service }}'
    enabled: yes
  notify: restart mariadb
