---

- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://10.60.129.132/repository/Yum_MariaDB/10.3/centos7-amd64/"
    gpgcheck: no
    enabled: yes

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mariadb_packages }}"

- name: enable mariadb
  service:
    name: '{{ mariadb_service }}'
    enabled: yes
  notify: restart mariadb
