---
# Variables for the HAproxy configuration

# HAProxy supports "http" and "tcp". For SSL, SMTP, etc, use "tcp".
mode: http

# Port on which HAProxy should listen
app_port: 5000

# Balancing Algorithm. Available options:
# roundrobin, source, leastconn, source, uri
# (if persistance is required use, "source")
balance: roundrobin


# List of backend servers.
haproxy_backend_servers: 
- name: app1
  address: 192.168.0.1
- name: app2
  address: 192.168.0.2


