---
# This role installs HAProxy and configures it.

- name: Add official Haproxy repository
  yum_repository:
    name: haproxy
    description: Official Haproxy repository
    baseurl: "http://10.240.201.50:8081/repository/centos-7"
    gpgcheck: no
    enabled: yes

- name: Ensure HAProxy is installed.
  yum: 
    name: haproxy
    state: present

- name: Configure the haproxy cnf file with hosts
  template: 
    src: haproxy.cfg.j2 
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service: 
    name: haproxy 
    state: started 
    enabled: yes
